export const COLLECTION_READ = 'COLLECTION_READ';
export const COLLECTION_SAVE = 'COLLECTION_SAVE';
export const COLLECTION_EDIT = 'COLLECTION_EDIT';
export const COLLECTION_DELETE = 'COLLECTION_DELETE';
